server:
  port: 8080
#jdbc
spring:
  datasource:
    url: jdbc:mysql://lbds01:3306
    username: root
    password: 123456
#mybatis
mybatis:
  mapper-locations: class:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
