server:
  port: 8172
#jdbc
spring:
  datasource:
    url: jdbc:mysql://lbds01:3306/luyi_tiger?characterEncoding=UTF-8
    username: root
    password: 123456
#dubbo的配置
  dubbo:
    #dubbo中的服务名称
    application: manager-service
    #dubbo的服务地址
    registry:
      address: 192.168.1.132:2181
    #zookeeper协议的名称
      protocol: zookeeper
    #dubbo的通讯协议名称
    protocol:
      name: dubbo
    #dubbo服务扫描路径
    base-package: com.ty.bmall
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
<<<<<<< HEAD:bmall-user/src/main/resources/application.yml
<<<<<<< HEAD:bmall-user/src/main/resources/application.yml
=======
#日志级别
logging:
  level:
     root: debug

>>>>>>> parent of 0ac4fb5... 完成DUBBO调整:bmall-manager-service/src/main/resources/application.yml
=======
#日志级别
logging:
  level:
    root: info

>>>>>>> ty_bmall_1:bmall-manager-service/src/main/resources/application.yml
