server:
  port: 8080
#jdbc
spring:
  datasource:
    url: jdbc:mysql://lbds01:3306/luyi_tiger?characterEncoding=UTF-8
    username: root
    password: 123456
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
<<<<<<< HEAD
=======
#日志级别
logging:
  level:
     root: debug

>>>>>>> parent of 0ac4fb5... 完成DUBBO调整
